### ISSUE TITLE
NGinx 500 error when visiting http://192.168.47.10/ after vagrant up

### ISSUE THREAD

**Issue by Truemedia** [richdynamix/magestead#19]
When running vagrant up on a fresh install and visiting http://192.168.47.10/ I get a 500 nginx error page instead of the installation greeting page.

This is what I get in the nginx error log:

2015/11/22 15:24:56 [error] 1880#0: *3 rewrite or internal redirection cycle while processing "/index.php", client: 192.168.47.1, server: _, request: "GET / HTTP/1.1", host: "192.168.47.10", referrer: "http://www.magestead.com/"

Not sure why it would fail if it is trying to get an external resource (assuming CSS and JS being pulled from the site looking at the index.php in public folder).

**Comment by richdynamix** [comment]
I have never encountered this before, I am on a Mac however the host operating system wouldn't make any difference in this case. Can you access an outside network from within the box? i.e `ping google.com` 

I notice you are using the IP address to route to the box rather than a host name. Although not mentioned in the docs you could install the vagrant plugin `Vagrant::Hostsupdater` which will read the domain you set in the `magestead.yaml` and automatically set your `/etc/hosts` file.

My intention was to create magestead without the requirement of plugins however looking at your error I think there is a bug in the NGINX config for boxes without the domain.

To install the plugin run `vagrant plugin install vagrant-hostsupdater` then you can provision your box again. Might be quicker and safer to just `vagrant destroy` then `vagrant up`

The default domain set in `magestead.yaml` is `magestead.dev`

**Comment by Truemedia** [comment]
Hi, again thanks for the reply. I did a ping inside the box with it up before and after rebuilding it and was able to ping google so network seems fine on the box.

I installed the hostupdater plugin and rebuilt my box but it doesnt seem to do anything to the etc/hosts file on my machine. Will try recloning the repo and repeat instructions, and manually add to my hosts file if needed.

**Comment by TomFoyster** [comment]
I'm getting the same issue. @Truemedia - did you ever get round this?

**Comment by Truemedia** [comment]
@TomFoyster Yes I did resolve this, but can't remember the solution sorry (Sorry hate to be that guy).
If you look around for any error logs, and check IPs that are being used that is the best thing to look into.

**Comment by warmothWeb** [comment]
@richdynamix @TomFoyster @Truemedia I am having the same problem. Anyone have a solution? Here is the error I get in the log:

`Failed to mount folders in Linux guest. This is usually because the "vboxsf" file system is not available. Please verify that the guest additions are properly installed in the guest and can work properly. The command attempted was:

mount -t vboxsf -o uid='id -u vagrant',gid='getent group vagrant | cut -d: -f3',actimeo=1 vagrant /vagrant
mount -t vboxsf -o uid='id -u vagrant',gid='id -g vagrant',actimeo=1 vagrant /vagrant

The error output from the last command was:

unknown mount option 'actimeo=1'
valid options:
rw           mount read write (default)
ro            mount read only
uid           =<arg> default file owner user id
gid           =<arg> default file owner group id
ttl             =<arg> time to live for dentry
iocharset =<arg> i/o charset (default utf8)
convertcp =<arg> convert share name from given charset to utf8
dmode     =<arg> mode of all directories
fmode      =<arg> mode of all regular files
umask      =<arg> umask of directories and regular files
dmask      =<arg> umask of directories
fmask       =<arg> umask of regular files`

**Comment by richdynamix** [comment]
Hi @warmothWeb 

I am not sure if this is the same issue as mentioned above. The issue you are experiencing sounds more like an issue with the shared folder being mounted. Which OS are you running on? 

Steven

**Comment by warmothWeb** [comment]
@richdynamix Windows 10

**Comment by richdynamix** [comment]
@warmothWeb Unfortunately I have not tested this with Windows as I am on a Mac however the default settings use NFS for shared folders, which is not available to Windows (natively). 

Although you could change the mount type to `smb` and add the correct mount options I must warn this is untested. 

There is a vagrant plugin that will give NFS support to windows. https://github.com/winnfsd/vagrant-winnfsd 

It might be worth giving this a try.

**Comment by richdynamix** [comment]
Closing this issue as unable to replicate as an issue.
