### ISSUE TITLE
Build box script 

### ISSUE THREAD

**Issue by lukaszduda** [richdynamix/magestead#20]
In my personal projects, works great :) Thx!

But can you share scripts that build the magestead development environment? As it is for laravel settler ? In my company corporate privacy policy does not allow us to install the software inside which we do not know what is :(

magestead for me and others people is not transparent like laravel homestead, homestead provides "laravel settler", the script that build box, this is not a secret ;)

**Comment by richdynamix** [comment]
Currently there are no scripts that build the box. The box was build manually using the latest version of the software in the `YUM` package manager where applicable. In some cases the software was build from source and retrieved from suppliers directly.

I know this is not an ideal situation but it allowed me more control over the software being installed at the time rather than learning a new provisioning suite like CHEF. I never intended magestead to be used within a corporate environment, I never thought anyone would want to :)

I have already started planning on the next version of magestead where one of the features allows for minimal box or full stack box. I have even thought about using chef for building the full stack box also.

In the interim, you could provision any CentOS box yourself and reference it in the Magestead.rb file. As long as you are using NGINX, PHP-FPM then it should work out the box, unless you are using other features which will need installed also.

**Comment by lukaszduda** [comment]
thanks for your answer, I try as you wrote ;)
