### ISSUE TITLE
Can't login to Magento

### ISSUE THREAD

**Issue by warmothWeb** [richdynamix/magestead#33]
I set up Magestead and got it running, but now I can't login to the Magento admin. I've tried a bunch of combinations of 'root' and 'vagrant', but nothing seems to work. I've tried updating the user privileges through MySql and I've tried to create a new user, but I still can't login. Any ideas?

**Comment by richdynamix** [comment]
Hi, 

When you installed the magento instance. Both magento and magento 2 will prompt you at command line with the username and password. 

A recent update add d cache flushing and reindexing after install and it's possible that you have missed the username and password at prompt since this is run after that. 

I will make an update to make that easier to see. In any case the password for both installations is. 

admin/password123

**Comment by warmothWeb** [comment]
Yeah, I don’t recall seeing a prompt.

Thanks!

Justin Hollender
Warmoth Guitar Products, Inc.
Webmaster/Web Development
PHONE 253-845-0403
www.warmoth.comhttp://www.warmoth.com/
